### ISSUE TITLE
Why inherit both 721 and 721Enumerable? 

### ISSUE THREAD

**Issue by stevieraykatz** [execute/ERC721-Example-Collection-Opensea-Compatible#1]
https://github.com/execute/ERC721-Example-Collection-Opensea-Compatible/blob/cf9606c33c48a9e9f918227148a4becc0d21f84f/Contract/Shard.sol#L10

Enumerable is already 721 so this might break because the inherited 721 will intersect the methods implicit to the 721Enum

**Comment by execute** [comment]
This is embarrassing on my end.
